import type { OnboardingStep } from "@/lib/onboarding/types";

export const CALENDARIO_TOUR_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    title: "Bem-vindo ao Calendário",
    body: "Aqui ficam os eventos importados do seu Outlook. Sua tarefa principal é categorizar cada compromisso: virou reunião com cliente, atividade interna ou pode ser ignorado.",
    placement: "center",
  },
  {
    id: "visao-geral",
    title: "Visão geral",
    body: "O contador abaixo do título mostra quantos eventos já passados ainda aguardam categorização. Eventos futuros não entram nessa conta — você categoriza depois que acontecem.",
    target: "calendario-header",
    placement: "bottom",
  },
  {
    id: "toolbar",
    title: "Filtros e sincronização",
    body: "Use os filtros para encontrar o que precisa de atenção. O botão Atualizar puxa novos eventos do Outlook. Alterne entre visualização em calendário ou lista.",
    target: "calendario-toolbar",
    placement: "bottom",
  },
  {
    id: "filtro-pendente",
    title: "Não categorizados",
    body: "Clique aqui para ver só os eventos que já ocorreram e ainda precisam de classificação. É o filtro que você usará com mais frequência.",
    target: "calendario-filtro-pendente",
    placement: "bottom",
  },
  {
    id: "demo-evento",
    title: "Evento não categorizado",
    body: "Eventos importados do Outlook aparecem assim, com o selo amarelo. Veja título, horário, local e quem participou antes de decidir.",
    demo: "evento",
    placement: "center",
  },
  {
    id: "demo-acoes",
    title: "Três caminhos",
    body: "Para cada evento você escolhe: Reclassificação Reunião (compromisso com cliente ou externo), Reclassificação Atividade (trabalho interno) ou Ignorar (não entra nas métricas).",
    demo: "evento-acoes",
    placement: "center",
  },
  {
    id: "demo-reuniao-abertura",
    title: "Categorizar como reunião",
    body: "Ao escolher Reunião, abre-se o formulário com dados do Outlook já preenchidos (título, horário, participantes). Você completa o restante.",
    demo: "reuniao-abertura",
    placement: "center",
  },
  {
    id: "demo-reuniao-tipo",
    title: "Tipo de reunião",
    body: "Defina o tipo: captação, fidelização, relacionamento etc. Isso alimenta o Dashboard e os relatórios por categoria.",
    demo: "reuniao-tipo",
    placement: "center",
  },
  {
    id: "demo-reuniao-cliente",
    title: "Cliente ou grupo",
    body: "Vincule a reunião a um cliente do VIOS ou a um grupo de clientes. O sistema pode sugerir automaticamente com base no título.",
    demo: "reuniao-cliente",
    placement: "center",
  },
  {
    id: "demo-reuniao-participantes",
    title: "Participantes",
    body: "Confirme quem participou — internos (equipe) e externos (convidados do Outlook). Isso define visibilidade e próximos passos.",
    demo: "reuniao-participantes",
    placement: "center",
  },
  {
    id: "demo-reuniao-resultado",
    title: "Resultado e próximos passos",
    body: "Após a reunião, registre o resumo e os próximos passos. Eles aparecem na aba Próximos passos para acompanhamento.",
    demo: "reuniao-resultado",
    placement: "center",
  },
  {
    id: "demo-reuniao-salvar",
    title: "Salvar categorização",
    body: "Ao salvar, o evento deixa de ser \"Não categorizado\" e passa a contar como reunião realizada no Dashboard e no timesheet.",
    demo: "reuniao-salvar",
    placement: "center",
  },
  {
    id: "finish",
    title: "Calendário concluído!",
    body: "Repita esse fluxo sempre que aparecer um evento pendente. Agora conheça o Dashboard para acompanhar suas métricas.",
    placement: "center",
    finishLabel: "Concluir tour",
    nextHref: "/dashboard",
    nextHrefLabel: "Ir para o Dashboard",
  },
];
